CREATE TYPE TARJA AS ENUM (
    'Preta',
    'Vermelha',
    'Vermelha sob restrição',
    'Sem tarja'
);
CREATE TYPE LISTA_CTRIBUTARIO AS ENUM ('POSITIVA', 'NEGATIVA', 'NEUTRA');
CREATE TYPE ANALISE_RECURSAL AS ENUM (
    'AR',
    '1',
    '2',
    '3',
    '5',
    '8',
    '9'
);
CREATE TABLE medicamentos (
    id SERIAL PRIMARY KEY,
    principio_ativo VARCHAR NOT NULL,
    cnpj VARCHAR NOT NULL,
    laboratorio VARCHAR NOT NULL,
    ggrem VARCHAR NOT NULL,
    registro VARCHAR,
    ean1 VARCHAR NOT NULL,
    ean2 VARCHAR,
    ean3 VARCHAR,
    produto VARCHAR NOT NULL,
    apresentacao VARCHAR NOT NULL,
    classe_terapeutica VARCHAR NOT NULL,
    tipo_produto VARCHAR,
    regime_preco VARCHAR NOT NULL,
    pf_sem_impostos REAL NOT NULL,
    pf_0 REAL,
    pf_12 REAL,
    pf_17 REAL,
    pf_17_alc REAL,
    pf_17_5 REAL,
    pf_17_5_alc REAL,
    pf_18 REAL,
    pf_18_alc REAL,
    pf_19 REAL,
    pf_20 REAL,
    pf_21 REAL,
    pf_22 REAL,
    pmvg_sem_impostos REAL,
    pmvg_0 REAL,
    pmvg_12 REAL,
    pmvg_17 REAL,
    pmvg_17_alc REAL,
    pmvg_17_5 REAL,
    pmvg_17_5_alc REAL,
    pmvg_18 REAL,
    pmvg_18_alc REAL,
    pmvg_19 REAL,
    pmvg_20 REAL,
    pmvg_21 REAL,
    pmvg_22 REAL,
    restricao_hospitalar BOOLEAN NOT NULL,
    cap BOOLEAN NOT NULL,
    confaz_87 BOOLEAN NOT NULL,
    icms_0 BOOLEAN NOT NULL,
    analise_recursal ANALISE_RECURSAL,
    lista_ctributario LISTA_CTRIBUTARIO NOT NULL,
    comercializacao BOOLEAN NOT NULL,
    tarja TARJA
);
COPY medicamentos
FROM '/medicamentos.csv' DELIMITER E'\t' CSV HEADER;