version: '3'

services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: promaxima
      POSTGRES_PASSWORD: 0kTpAC3%l9!M$W5q
      POSTGRES_DB: promaxima
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data

  django:
    build: .docker/django
    command: python3 manage.py runserver 0.0.0.0:8000
    environment:
      POSTGRES_NAME: promaxima
      POSTGRES_USER: promaxima
      POSTGRES_PASSWORD: 0kTpAC3%l9!M$W5q
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    ports:
      - "8000:8000"
    volumes:
      - ./src:/code
    depends_on:
      - db
