# Generated by Django 4.2.3 on 2023-07-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principio_ativo', models.CharField()),
                ('cnpj', models.CharField()),
                ('laboratorio', models.CharField()),
                ('ggrem', models.CharField()),
                ('registro', models.CharField(blank=True, null=True)),
                ('ean1', models.CharField()),
                ('ean2', models.CharField(blank=True, null=True)),
                ('ean3', models.CharField(blank=True, null=True)),
                ('produto', models.CharField()),
                ('apresentacao', models.CharField()),
                ('classe_terapeutica', models.CharField()),
                ('tipo_produto', models.CharField(blank=True, null=True)),
                ('regime_preco', models.CharField()),
                ('pf_sem_impostos', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('pf_0', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('pf_12', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('pf_17', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('pf_17_alc', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('pf_17_5', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('pf_17_5_alc', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('pf_18', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('pf_18_alc', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('pf_19', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('pf_20', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('pf_21', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('pf_22', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('pmvg_sem_impostos', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('pmvg_0', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('pmvg_12', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('pmvg_17', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('pmvg_17_alc', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('pmvg_17_5', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('pmvg_17_5_alc', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('pmvg_18', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('pmvg_18_alc', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('pmvg_19', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('pmvg_20', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('pmvg_21', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('pmvg_22', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('restricao_hospitalar', models.BooleanField()),
                ('cap', models.BooleanField()),
                ('confaz_87', models.BooleanField()),
                ('icms_0', models.BooleanField()),
                ('analise_recursal', models.TextField(blank=True, null=True)),
                ('lista_ctributario', models.TextField()),
                ('comercializacao', models.BooleanField()),
                ('tarja', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'medicamentos',
                'managed': False,
            },
        ),
    ]
